name: travelappflutter
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.24.3'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.2.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  pin_code_fields: 8.0.0
  sms_autofill: ^2.0.0
  intl: ^0.17.0
  iconsax: ^0.0.8
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  image_picker: ^0.8.5
  file_picker: ^4.6.1
  geolocator: ^10.0.0
  geocoding: ^2.0.5  
  url_launcher: ^6.3.0
  flutter_bloc: ^8.0.0  # Phiên bản mới nhất
  flutter_form_builder: ^8.0.0



dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
